const menuButton=document.querySelector('.menu-toggle'),menu=document.getElementById('menu');
menuButton?.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});
menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');menuButton?.setAttribute('aria-expanded','false')}));
const leadDialog=document.getElementById('lead-dialog');
document.querySelectorAll('.open-dialog').forEach(b=>b.addEventListener('click',()=>{leadDialog.showModal();document.body.classList.add('dialog-open')}));
document.querySelector('.dialog-close')?.addEventListener('click',()=>leadDialog.close());
leadDialog?.addEventListener('close',()=>document.body.classList.remove('dialog-open'));
leadDialog?.addEventListener('click',e=>{if(e.target===leadDialog)leadDialog.close()});
const lightbox=document.getElementById('lightbox'),lightboxImage=lightbox?.querySelector('img');
document.querySelectorAll('.gallery-item').forEach(item=>item.addEventListener('click',()=>{lightboxImage.src=item.dataset.full;lightboxImage.alt=item.querySelector('img').alt;lightbox.showModal()}));
lightbox?.querySelector('button')?.addEventListener('click',()=>lightbox.close());
lightbox?.addEventListener('click',e=>{if(e.target===lightbox)lightbox.close()});
document.querySelectorAll('[data-lead-form]').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const status=form.querySelector('.form-status'),submit=form.querySelector('button[type="submit"]');status.className='form-status';status.textContent='Отправляем заявку…';submit.disabled=true;try{const response=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});let result={};if((response.headers.get('content-type')||'').includes('application/json'))result=await response.json();if(!response.ok)throw new Error(result.message||'Не удалось отправить заявку.');status.classList.add('success');status.textContent=result.message||'Заявка отправлена. Мы свяжемся с вами.';form.reset()}catch(error){status.classList.add('error');status.textContent=`${error.message||'Не удалось отправить заявку.'} Позвоните нам по номеру +7 (495) 123-45-67.`}finally{submit.disabled=false}}));
document.getElementById('year').textContent=new Date().getFullYear();
